spring.application.name=backend

spring.datasource.url=jdbc:postgresql://db:5432/appdb
spring.datasource.username=app
spring.datasource.password=secret


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql